# Generated by Django 4.1.1 on 2023-01-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleemissions', '0002_remove_car_mpg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
