# Generated by Django 4.1.1 on 2023-01-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicleemissions', '0003_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=200)),
                ('carModel', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('make2', models.CharField(max_length=200)),
                ('carModel2', models.CharField(max_length=200)),
                ('year2', models.IntegerField()),
            ],
        ),
    ]
